### ISSUE TITLE
Adjusting default options configuration for highest utility

### ISSUE THREAD

**Issue by leoroos** [907th/vim-auto-save#14]
I know the plugin is based on the Rubymine behavior which saves automatically every 200ms.
But vim feels different then Rubymine.

A switch to insert mode is atomic for me. I change something and am back in normal mode as soon as possible. So a save during that time is unnecessary and even disadvantages for me, because it disrupts my writing and splits my changes into multiple which are then not represented in my undo/repeat list as they would be in vim without vim-auto-save. 

200 ms update time in normal mode often causes problems for me with other plugins and syntax highlighting. So I increase it or switch it off completely. But at the same time I want to be sure, that as soon as I use the file (read it with another program, execute it) the file is in the most recent state. So I add the auto save event TextChanged which operates in normal mode and saves on every text change.

I would like to know how other people are using vim-auto-save. And whether it would make sense to adjust the default options based on that, to have an installation which works for as many people out of the box as possible.

**Comment by 907th** [comment]
@leoroos Proposed configuration looks very reasonable for me!

**Comment by alexdunn** [comment]
I ran into problems with the way auto save triggers.  Setting updatetime to 200 makes it impossible to use CursorHold for what it's meant: To find out when the user has held the cursor in one place for a while.  I think it would make a lot more sense if it relied less on updatetime (CursorHold) and more on TextChanged and InsertLeave.

**Comment by 907th** [comment]
@alexdunn Thanks! I will switch it to `TextChanged` when I have time for it.
