### ISSUE TITLE
Breaks selecting recently pasted text with `[v`]

### ISSUE THREAD

**Issue by dechimp** [907th/vim-auto-save#15]
When I have vim-auto-save enabled, I cannot use this helpful trick to select recently pasted text  http://vim.wikia.com/wiki/Selecting_your_pasted_text

When you use 
```
`[v`]
```
, it selects the entire file.

**Comment by leoroos** [comment]
Could you give some more details?
What vim-auto-save configuration do you use, do you get any errors?

**Comment by dechimp** [comment]
The only configuration that makes it break is enabling the plugin in my vimrc using 
```
:let g:autosave = 1
```
When I do backtick + [ or  singlequote + [ I am taken to the beginning of the file, rather than to the beginning of the last pasted text.

**Comment by 907th** [comment]
@dechimp The same happens when you just use `:w` (and we use it for saving in `vim-auto-save`). I'm not sure we're able to fix it.

**Comment by dechimp** [comment]
Ah.  That's a shame. At least we got to the bottom of the issue.
