### ISSUE TITLE
Breaks CTRL-X Mode

### ISSUE THREAD

**Issue by waivek** [907th/vim-auto-save#18]
I'm using gvim on Windows. I used Vundle to install the plugin from [here](https://github.com/vim-scripts/vim-auto-save). When this plugin is loaded, if I try to enter `^X mode` by pressing CTRL-X in `INSERT` mode, it immediately exits back into the general `INSERT` mode. If I comment out the line `Plugin 'vim-scripts/vim-auto-save'` and change it to `" Plugin 'vim-scripts/vim-auto-save'` then I can enter and stay in `^X mode`. I'm not completely familiar with VimL for plugins otherwise I would try toggling some of the `g:` variables. Could you tell me if there is any fix for this?

**Comment by 907th** [comment]
@waivek Thanks for reporting it! This happens because we use `au CursorHoldI * ...` callback. As a temporary solution you may disable the plugin in insert mode (it will still work in normal mode) with:
```
" .vimrc
let g:auto_save_in_insert_mode = 0
```

**Comment by waivek** [comment]
This fixed it. Thank You.
