### ISSUE TITLE
per buffer option ?

### ISSUE THREAD

**Issue by teto** [907th/vim-auto-save#29]
Is it possible to enable autosave on a per buffer basis ? 

I like to enable it for python but would prefer not saving buffers with other ft.
Thanks for the plugin.

**Comment by 907th** [comment]
@teto Hello! It is not possible right now, but I think it is not too hard to implement.

**Comment by teto** [comment]
I've pushed a first attempt here 
https://github.com/teto/vim-auto-save/tree/per_buffer .
I have a pb though,  for instance I save on "FocusLost" exclusively, when I lose focus it will autosave only the current buffer, so I would need a loop (or sthg like forallbuffers do {})to call AutoSave for every buffer ?!

**Comment by 907th** [comment]
Thank you for your work! You can create a PR and we shall move the discussion there.

 I should added a new option to enable per-buffer behaviour (e.g. `g:auto_save_per_buffer` default = false).

I see your comment on trying to use `bufdo`, it seems to be a solution to your problem.

**Comment by teto** [comment]
yeah bufdo looks like the way to go but it changes vim focus so it's actually a bit more complex then that: http://vim.wikia.com/wiki/Run_a_command_in_multiple_buffers
Don't have the time to dig deeper now.

**Comment by teto** [comment]
fixed in recent commits
