### ISSUE TITLE
blocked by this plugin.

### ISSUE THREAD

**Issue by crazy-canux** [907th/vim-auto-save#31]
When I add this plugin to my vim.
vim  blocked.
After I delete it, vim works again.

**Comment by 907th** [comment]
Hello, @crazy-canux! It is not enough details to help you. Try to use minimalistic `.vimrc` with this plugin only and see if it works.

**Comment by 907th** [comment]
@crazy-canux I'm closing this one for now. Please, reopen if you still have this problem.
