### ISSUE TITLE
TextChanged Error

### ISSUE THREAD

**Issue by todd-bush** [907th/vim-auto-save#32]
receiving this error:

zsh 1796 [1] % vi .vim/bundle/vim-auto-save/plugin/AutoSave.vim
Error detected while processing /Users/toddbush/.vim/bundle/vim-auto-save/plugin/AutoSave.vim:
line   46:
E216: No such group or event: TextChanged * nested call AutoSave()
Press ENTER or type command to continue

vim version:

zsh 1796 [1] % vi --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 14 2016 16:06:49)
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments
-conceal +cryptv +cscope +cursorbind +cursorshape +dialog_con +diff +digraphs
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() -gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm +multi_byte +multi_lang -mzscheme +netbeans_intg -osfiletype
+path_extra -perl +persistent_undo +postscript +printer -profile +python/dyn
-python3 +quickfix +reltime -rightleft +ruby/dyn +scrollbind +signs
+smartindent -sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white -tcl +terminfo +termresponse +textobjects +title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra +viminfo
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -D_FORTIFY_SOURCE=0 -Iproto -DHAVE_CONFIG_H -arch i386 -arch x86_64 -g -Os -pipe
Linking: gcc -arch i386 -arch x86_64 -o vim -lncurses

**Comment by 907th** [comment]
Hello @todd-bush! Thank you for reporting this! It seems like you're using old Vim version which has no support for `TextChanged` event. I have [updated the plugin](https://github.com/907th/vim-auto-save/commit/839d674a04863a5f1872ec8e3ef7539e42de6dcf) to handle such situation and show an appropriate message to the user.

Vim 7.4 is required for plugin to work correctly with a default configuration. It also can work with older Vim version, but you will need to manually configure when to auto-save a file. Please, use `g:auto_save_events` option.

**Comment by todd-bush** [comment]
Ah.  thanks @907th.  I see the new error message.  I'll upgrade my vim.  Closing this issue.
