### ISSUE TITLE
How to activate auto-save per filetype?

### ISSUE THREAD

**Issue by adeluccar** [907th/vim-auto-save#33]
Hi,
I can't seem to make it toggle for ruby files only.
I tried:
```
augroup auto_save_for_ruby
  autocmd!
  autocmd Filetype *.rb :AutoSaveToggle()
augroup END
```
Any suggestion on how to make this happen?
—Alberto

**Comment by 907th** [comment]
Hello! @adeluccar!
This is not possible with the current version of the plugin.
We set `au` for all file types (this [line](https://github.com/907th/vim-auto-save/blob/master/plugin/AutoSave.vim#L48)).

**Comment by cornop** [comment]
Is this something that would be easy to implement? This is currently a blocker for me using this plugin, since I only want to use this plugin for programming and not editing in general.

**Comment by 907th** [comment]
@cornop @adeluccar We now have `g:auto_save_presave_hook` which you could use to prevent auto-saving for some reason:

```vim
# .vimrc
let g:auto_save_presave_hook = 'call AbortIfNotRuby()'

function! AbortIfNotRuby()
  if &filtype != 'ruby'
    let g:auto_save_abort = 1
  endif
endfunction
```

PS. Pre-save hook only called when auto-save enabled.
PPS. I'm not tested the code. So be aware of bugs :) Happy hacking!

**Comment by cornop** [comment]
@907th This works, cheers!

(there's a typo: filtype should be filetype)

**Comment by adeluccar** [comment]
Closing the issue since @907th provided a solution [above](https://github.com/907th/vim-auto-save/issues/33#issuecomment-275641614).
