### ISSUE TITLE
Undo does not work when using this plugin

### ISSUE THREAD

**Issue by svanharmelen** [907th/vim-auto-save#37]
I'm using NeoVim 0.2 on macOS 10.12.5.

When Using the plugin with default options, I can no longer undo changes made in normal mode (maybe also other changes, but didn't test specifically). When I set `leg g:auto_save_events = ["InsertLeave"]` it seems to work as expected again.

Is this a known problem or bug? Or can I tweak this with config settings?

**Comment by svanharmelen** [comment]
Additionally I notice that with `leg g:auto_save_events = ["InsertLeave"]` a change made in insert mode the is auto saved when leaving insert mode, takes to undo command to actually undo the last edit. The first time pressing `u` doesn't seem to do anything and then pressing it again undo's the change.

**Comment by 907th** [comment]
@svanharmelen This is unknown bug for me. Thanks for reporting!

**Comment by svanharmelen** [comment]
Check! @907th let me know if there is anything I can do to help troubleshoot this, as it is now preventing me from using this plugin which otherwise looks really nice and helpful :wink:

**Comment by svanharmelen** [comment]
I think the problem is due to a combination of plugins that I'm using. The plugins involved are `vim-go` and `ALE` which both do stuff when a file is saved. So I'm guessing this combination results in these plugins getting into each others ways and that is isn't a bug in this plugin after all...

**Comment by dlip** [comment]
This may help, it disables the plugin when you try to undo:
```lua
  condition = function(buf)
    local fn = vim.fn
    local undotree = vim.fn.undotree()
    if undotree.seq_last ~= undotree.seq_cur then
      return false -- don't try to save again if I tried to undo. k thanks
    end
  end
```
