### ISSUE TITLE
Undo list is modified for every repetition of a macro

### ISSUE THREAD

**Issue by Asheq** [907th/vim-auto-save#41]
First-off: Great plugin! Auto-saving is a revelation.

I've run into a minor annoyance: Let's say I record a macro with `qqAhello<Esc>q`. Then, I run the macro 22 times with `22@q`.

Normally (with auto-save disabled), running the macro 22 times as I did is counted as one change. So I can undo all of it with a single `u`.

With auto-save enabled, each of the 22 runs is counted as a separate change. I would have to press `u` 22 times or `22u` to get back to where I was.

Not sure what the best way to deal with this is or if it should even be dealt with. Just want to bring it to your attention.

**Comment by 907th** [comment]
@Asheq Thank you for your report! Unfortunately I see no way of fixing it :(
