### ISSUE TITLE
Isn't working as desired with TextChangedI

### ISSUE THREAD

**Issue by MahbubAlam231** [907th/vim-auto-save#43]
I added `TextChangedI` as an event. `vim-auto-save` abruptly shifts cursor position to the left while inserting text. Guess it is a `escape` and entering insert mode with `i` issue.

**Comment by 907th** [comment]
@MahbubAlam231 I've just tested `TextChangedI` and do not see any issues with cursor shifting (neovim v0.2.2). AutoSave doesn't send `Esc` / `i` keys. You should try to disable all other plugins and custom configs/mappings to check if there any conflicts.

**Comment by MahbubAlam231** [comment]
I'm using Vim 7.4, could that be any issue?

**Comment by 907th** [comment]
@MahbubAlam231 I don't know 😕

**Comment by MahbubAlam231** [comment]
Anyway thanks.
