### ISSUE TITLE
Normal mode only?

### ISSUE THREAD

**Issue by mastertinner** [907th/vim-auto-save#45]
Saving on any change in insert mode can be quite a lot and it leads to some integrations/plugins flickering. Wouldn't it make more sense to only auto save once I'm back in normal mode? Could this be a configurable option or even the default? Usually, in Vim, going into insert mode, changing multiple things and then going back into normal mode only counts as one change so I would also expect this plugin to only save after I've gone back into normal mode.

Any feedback?

**Comment by 907th** [comment]
@mastertinner This is documented in README:
> The events on which AutoSave will perform a save can be adjusted using the `g:auto_save_events` option.

By default it saves on `InsertLeave` and `TextChanged` events only. So it doesn't save (by default) until you leave insert mode.

**Comment by mastertinner** [comment]
@907th, my sincere apologies! I had https://github.com/vim-scripts/vim-auto-save installed instead of your plugin and opened the issue in the wrong repo. Since, as you described, your plugin behaves as I would expect it, I'll switch to using yours. Thanks!

**Comment by 907th** [comment]
@mastertinner I'm glad to help you! [vim-scripts.org](http://vim-scripts.org/) have very outdated version of vim-auto-save plugin. All their plugins are scraped from vim.org. I don't known why their version of vim-auto-save was not updated since 2017.
