### ISSUE TITLE
Duplicate entry is created in undo history

### ISSUE THREAD

**Issue by Asheq** [907th/vim-auto-save#53]
This duplicate entry is added after an **InsertLeave** and after the **user moves the cursor**.

### To reproduce:
1. Enter insert-mode.
2. Type anything.
3. Exit insert mode.

    * Autosave is triggered and undo history is updated, as expected.

4. Move the cursor using any motion.

    * Undo list is updated again with no actual diff, which is _not_ expected.

Here is an example below. I am using [undotree](https://github.com/mbbill/undotree) to visualize the undo history.
![example](https://user-images.githubusercontent.com/4657140/71749105-5d2d2d00-2e29-11ea-826f-518502876e72.gif)

**Comment by Asheq** [comment]
FYI: This issue (as well #41) goes away when I trigger an auto-save on only `CursorHold` and `CursorHoldI` events.

```
let g:auto_save_events = ["CursorHold", "CursorHoldI"]
set updatetime=300
```

So far, things are working well for me using these settings!

**Comment by rjshrjndrn** [comment]
I think OP has a valid point. Plugin creates some modification,( that comes up in undo history) in every event. @Asheq, I tried with your settings.

**Comment by 907th** [comment]
@Asheq @rjshrjndrn Hello! I have no time to investigate and fix this issue, sorry! But if you know how to fix that a PR is very welcome!

**Comment by tek** [comment]
my solution:

```vim
let g:undo_skip_max_lines = 1000

function! Undo(it) abort "{{{
  function! Lines() abort "{{{
    return nvim_buf_get_lines(0, 0, g:undo_skip_max_lines, v:false)
  endfunction "}}}
  if nvim_buf_line_count(0) < g:undo_skip_max_lines && a:it < 10
    let pre = Lines()
    normal! u
    let post = Lines()
    if pre == post
      return Undo(a:it + 1)
    endif
  else
    normal! u
  endif
endfunction "}}}

nnoremap u <cmd>call Undo(0)<cr>
```

skip empty changes in undo.
