### ISSUE TITLE
Save file, after window lose focus.

### ISSUE THREAD

**Issue by seriiserii825** [907th/vim-auto-save#59]
Hi. 
Thanks for plugin. 

I need behaviour like vscode or phpstorm, when save works, when window lose focus. 
How can i implement this?

**Comment by 907th** [comment]
Hello! You can configure a set of events which trigger auto-save with [g:auto_save_events](https://github.com/907th/vim-auto-save#events) setting. Look at [WinLeave](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#WinLeave) / [BufLeave](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#BufLeave) events.

**Comment by seriiserii825** [comment]
Thansk a lot!!!!!

That solved my problem 

`let g:auto_save_events = ["FocusLost"]
`
