### ISSUE TITLE
Enable auto-save only on git folders

### ISSUE THREAD

**Issue by EduardGol** [907th/vim-auto-save#60]
How i can configure vim-auto-save, to save only under git repositories. Now are saving all my files.

**Comment by 907th** [comment]
Hello, @EduardGol! If you are familiar with Vim scripting language a little you will be able to write [pre-save hook](https://github.com/907th/vim-auto-save#prepostsave-hooks) which checks a path of the current file.

**Comment by EduardGol** [comment]
Thanks, i have find.

let g:auto_save = 1 
" This will run AbortIfNotGitDirectory function before each save
let g:auto_save_presave_hook = 'call AbortIfNotGitDirectory()'
" Example hook from vim-auto-save-git-hook plugin
function! AbortIfNotGitDirectory()
  if isdirectory(".git")
    let g:auto_save_abort = 0
  else
    let g:auto_save_abort = 1
  endif
endfunction

If you use vim-nerdtree or other file browser for vim, must to set before root folder, for vim understant he is in git folder.
