### ISSUE TITLE
Breaks vim-surround with vim-repeat

### ISSUE THREAD

**Issue by aaronjensen** [907th/vim-auto-save#8]
If you have auto save enabled, `.` no longer works when doing a surround command. For example, if you do a `cs'"` to change single quotes to double quotes, then hit `.` to repeat it elsewhere, it does not work. Disabling autosave works.

**Comment by 907th** [comment]
@aaronjensen Surprisingly `cs` does not work for me without auto-save too. O_o

**Comment by aaronjensen** [comment]
```viml
let g:auto_save_events = ["InsertLeave", "TextChanged"]
```

seems to help things

**Comment by aaronjensen** [comment]
autosave on `InsertLeave` appears to be the culprit... if I get rid of that, things seem to work better.

**Comment by 907th** [comment]
@aaronjensen How exactly better?

**Comment by aaronjensen** [comment]
@907th in my brief trialling, it seems to make `.` work work consistently and `u` undo the entire change from a `cs'"` or whatever in one step instead of two. 

I think the problem was `InsertLeave` was firing in the middle or a `vim-surround` action which caused `vim-repeat` to not be able to do its job properly.

**Comment by aaronjensen** [comment]
This was apparently a bug in vim that was recently fixed.
